# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3d58ca592ccb888b1cf0bf6e567672c9fb5fdf36d243924035a162dc49c80541c382791b0d13d7d2146c363ac3cc5bbd44fb6d802456327aa6fbc908ca125532

test:
  secret_key_base: f3b4920ef2916e04d10be41fd4f9e6dafa550e7e01be00a4cd06b228031af0ef0ae7255928bc42d03da1fb942fb13e6e0106ee980bf8c1ed3c95fda1c91b3b26

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
